# ============================================================================
# Financial Data Analysis and Planning Dashboard - Server
# BIOL 185 Group Project
# ============================================================================

# Auto-Install and Load Required Packages ----
required_packages <- c(
  "shiny", "bslib", "bsicons", "shinyWidgets", "tidyverse", "WDI", # Added bslib, bsicons; removed shinydashboard (optional but kept just in case of legacy calls)
  "plotly", "DT", "scales", "corrplot", "sf", 
  "rnaturalearth", "rnaturalearthdata", "viridis", "readxl"
)

# Check for missing packages
missing_packages <- required_packages[!(required_packages %in% installed.packages()[,"Package"])]

# Auto-install missing packages
if (length(missing_packages) > 0) {
  cat("=======================================================\n")
  cat("Installing missing packages for the first time...\n")
  cat("This may take a few minutes.\n")
  cat("=======================================================\n\n")
  cat("Packages to install:", paste(missing_packages, collapse = ", "), "\n\n")
  
  install.packages(missing_packages, dependencies = TRUE)
  
  cat("\n=======================================================\n")
  cat("Installation complete!\n")
  cat("=======================================================\n\n")
}

# Load Required Libraries ----
library(shiny)
library(bslib)
library(bsicons)
library(tidyverse)
library(plotly)
library(DT)
library(scales)
library(corrplot)
library(sf)
library(rnaturalearth)
library(viridis)
library(readxl)

# Source Server Logic ----
source("modules/macro/server/server_time_series.R")
source("modules/macro/server/server_relationships.R")
source("modules/macro/server/server_correlations.R")
source("modules/macro/server/server_global_map.R")
source("modules/macro/server/server_regional_trends.R")
source("modules/macro/server/server_states.R")
source("modules/macro/server/server_unemployment.R")
source("modules/macro/server/server_commodity.R")
source("modules/macro/server/server_statistical_analysis.R")
source("modules/macro/server/server_data_table.R")

source("modules/personal_finance/server/server_savings.R")
source("modules/personal_finance/server/server_loans.R")
source("modules/personal_finance/server/server_planning_guide.R")

source("modules/retirement/server/server_simulator.R")
source("modules/retirement/server/server_scenarios.R")

# Define Server ----
function(input, output, session) {
  
  # Load Data directly from RDS (must be generated by ETL first)
  data_path <- "data/world_bank_wdi/wdi_clean.rds"
  
  if (!file.exists(data_path)) {
    stop("Data file not found! Please run 'data/world_bank_wdi/ETL_world_bank_wdi.Rmd' first to generate the data.")
  }
  
  macro_data <- readRDS(data_path)
  
  # Create Reactive Values for Shared State ----
  shared_state <- reactiveValues(
    selected_countries = c("United States", "China", "Germany", "Japan", "India"),
    year_range = c(2000, 2023),
    current_indicator = "gdp_per_capita"
  )
  
  # Module 1: Global Macroeconomic Explorer Servers ----
  time_series_server(input, output, session, macro_data, shared_state)
  relationships_server(input, output, session, macro_data, shared_state)
  commodity_server(input, output, session, macro_data, shared_state)
  correlations_server(input, output, session, macro_data, shared_state)
  global_map_server(input, output, session, macro_data, shared_state)
  regional_trends_server(input, output, session, macro_data, shared_state)
  states_server(input, output, session)
  unemployment_server(input, output, session, shared_state)
  statistical_analysis_server(input, output, session, macro_data, shared_state)
  data_table_server(input, output, session, macro_data, shared_state)
  
  # Module 2: Personal Finance Tools Servers ----
  #savings_server(input, output, session)
  #loans_server(input, output, session)
  #planning_guide_server(input, output, session)
  
  # Module 3: Retirement Risk Simulator Servers ----
  #simulator_server(input, output, session)
  #scenarios_server(input, output, session)
  
  # Home Page Navigation (Updated for bslib page_navbar id)
  observeEvent(input$btn_goto_macro, {
    updateNavbarPage(session, "nav", selected = "macro_time_series")
  })
  
  observeEvent(input$btn_goto_finance, {
    updateNavbarPage(session, "nav", selected = "pf_savings")
  })
  
  observeEvent(input$btn_goto_retirement, {
    updateNavbarPage(session, "nav", selected = "ret_simulator")
  })
  
}
